name: Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # Necessary for the action to work until the following issue is fixed:
      # https://github.com/EPMatt/reviewdog-action-prettier/issues/34
      - name: Downgrade npm to v8
        run: npm install -g npm@8
      - name: Format
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          level: warning
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          prettier_flags: '--check "src/**/*.{ts,tsx}"'
